# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: pretty

nav:
  - title: Home
    url: /
  - title: fail
    url: /fail/
  - title: fastai
    url: /fastai/
  - title: git&Blog
    url: /git&Blog/
  - title: study
    url: /study/
  - title: UiPath
    url: /UiPath/UiPath/
  - title: UiPath_studylog
    url: /UiPath/UiPath_studylog/
  - title: UP_schedule&map
    url: /UiPath/UP_schedule&map/
  - title: Build your first automation process with Studio
    url: /UiPath/Build your first automation process with Studio/