# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: :title/
tags:
  permalink: /tags/:tag/
nav:
  - title: Home
    url: /
  - title: ・UiPath
    url: /UiPath index/
  - title: ・Others
    url: /Others index/
  - title: ☆git&Blog
    url: /git&Blog/
  - title: ゜UP_Schedule&Map
    url: /Schedule_Map/
  - title: ゜Variables, Constants and Arguments in Studio
    url: /Variables, Constants and Arguments in Studio/