# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: pretty

nav:
  - title: Home
    url: /
  - title: ・UiPath_index
    url: /UiPath/UiPath_index/
  - title: git&Blog
    url: /git&Blog/
  - title: ゜UiPath
    url: /UiPath/UiPath/
  - title: ゜UiPath_StudyLog
    url: /UiPath/UiPath_studylog/
  - title: ゜UP_schedule&map
    url: /UiPath/UP_schedule&map/
  - title: ゜Build your first automation process with Studio
    url: /UiPath/c2/