# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

description: Acctually It's a NoteBook

nav:
  - title: Home
    url: /
  - title: fail
    url: /fail.md
  - title: fastai
    url: /fastai.md
  - title: git&Blog
    url: /git&Blog.md
  - title: UiPath
    url: /Uipath/
  - title: study
    url: /study.md
  - title: unipath_studylog
    url: /Uipath/unipath_studylog.md