# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: pretty

nav:
  - title: Home
    url: "https://ukibune.github.io"
  - title: fail
    url: "https://ukibune.github.io/fail"
