# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-archives

jekyll-archives:
  enabled: [year, month, tag] # 启用年、月、标签归档
  layout: tag
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year/:month/'
    tag: '/tag/:tag/'

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: :title/


nav:
  - title: Home
    url: /
  - title: ・UiPath
    url: /UiPath/
  - title: ・Others
    url: /Others/
  - title: ☆git&Blog
    url: /git-Blog/
  - title: ゜UP_Schedule&Map
    url: /UP-Schedule-Map/
  - title: ゜Control Flow in Studio
    url: /c5/