# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: :title/


nav:
  - title: Home
    url: /
  - title: ・UiPath
    url: /UiPath/
  - title: ・Others
    url: /Others/
  - title: ☆git&Blog
    url: /git-Blog/
  - title: ゜UP_Schedule&Map
    url: /UP-Schedule-Map/
  - title: ゜Control Flow in Studio
    url: /c5/

collections:
    tag:
        permalink: /tags/:title
        output: true

defaults:
  -
    scope:
      path: ""
      type: "tag"
    values:
      layout: tag_page