# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

description: Acctually It's a NoteBook

nav:
  - title: Home
    url: /index.md
  - title: fail
    url: /fail
  - title: fastai
    url: /fastai/