# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-archives
- jekyll-paginate
- jekyll-toc

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: :title/
layout: default

nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts
  - title: ☆
    url: /show-tag

jekyll-archives:
  enabled: [tags]
  layout: tag
  permalink: "/tag/:tag/"
  paginate: 10
