# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: pretty

nav:
  - title: Home
    url: /
  - title: ・UiPath
    url: /UiPath/UiPath/
  - title: ・Others
    url: /Others/Others/
  - title: ☆git&Blog
    url: /Others/git&Blog/
  - title: ゜UP_UP_Schedule&Map
    url: /UiPath/UP_UP_Schedule&Map/
  - title: ゜Variables, Constants and Arguments in Studio
    url: /UiPath/c4/