# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-archives
- jekyll-paginate

title: Ukibune's Blog
description: Acctually It's a NoteBook
baseurl: "/"
permalink: :title/
layout: default

nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts
  - title: ゜UP_Schedule&Map
    url: /UP-Schedule-Map/
  - title: ゜Control Flow in Studio
    url: /c5/

jekyll-archives:
  enabled: [tags]
  layout: tag
  permalink: "/tag/:tag/"
  paginate: 10