# _config.yml

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

description: Acctually It's a NoteBook

nav:
  - title: Home
    url: /
  - title: UiPath
    url: /UiPath.md
  - title: UP_schedule&map
    url: /UP_schedule&map.md
